### ISSUE TITLE
`usb.ids` package does not exist on older Debian versions

### ISSUE THREAD

**Issue by MaxiBoether** [lpirl/ansible-roles#5]
I have not taken a deeper look at that and just ignored the error for now. Maybe this is easily fixable, just wanted to leave a note:

In the `managed_host` role, when installing packages for getting hardware information, we are trying to install `usb.ids`, which seems to exist for sid Debian (testing), but at least not on Stretch or below.

**Comment by lpirl** [comment]
True; thank for reporting. Will commit a fix soon.

**Comment by MaxiBoether** [comment]
Thank you!

**Comment by lpirl** [comment]
BTW you also could have set
```
system_information_packages_extra:
  usb.ids: absent
```
in your variables.
