### ISSUE TITLE
blockinfile does not support `force`

### ISSUE THREAD

**Issue by MaxiBoether** [lpirl/ansible-roles#6]
In `nginx.yml` (managed_host), we are using  `force: yes`. This tasks fails with the following error:

Unsupported parameters for (blockinfile) module: force Supported parameters include: attributes, backup, block, create, group, insertafter, insertbefore, marker, marker_begin, marker_end, mode, owner, path, selevel, serole, setype, seuser, state, unsafe_writes, validate

I am using Ansible 2.10.

I cannot find anything about `force` in the documentation as well: https://docs.ansible.com/ansible/2.5/modules/blockinfile_module.html

Should we remove force?

**Comment by lpirl** [comment]
True! Although I am irritated that I did not see the error so far. Anyway, will commit a fix soon.

**Comment by MaxiBoether** [comment]
Thanks for providing a fix.
