### ISSUE TITLE
`shim-signed` package not available

### ISSUE THREAD

**Issue by MaxiBoether** [lpirl/ansible-roles#9]
Similar to my other issue about `usb.ids`, I have not read up on this package yet. 

The managed_node role tries to install/uninstall `shim-signed`, which is not available on Debian 10 or below and hence fails the task. Maybe we should add a check for that?

**Comment by lpirl** [comment]
Are you sure your statement is true for Debian 10/Buster?
[The packages seems to be available there](https://packages.debian.org/buster/shim-signed).
We can default to not installing the package for Debian pre-Buster.

**Comment by MaxiBoether** [comment]
Oh, yes, indeed. It is not available on stretch (9) and below. I will provide a fix: https://github.com/lpirl/ansible-roles/pull/12

**Comment by lpirl** [comment]
Thanks for the #12, merged into [branch `debian-8-compat`](/lpirl/ansible-roles/tree/debian-8-compat) to not clutter master too much with code for Debian Jessie.
